name: Build

on:
  workflow_call:
    inputs:
      upload:
        required: false
        type: boolean
        default: false
      artifact-name:
        required: false
        type: string
        default: "slopify"
    outputs:
      zip-path:
        description: "Path to the built ZIP file"
        value: ${{ jobs.build.outputs.zip-path }}
      artifact-name:
        description: "Name of the built ZIP file"
        value: ${{ jobs.build.outputs.zip-path }}


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix
    - name: Build
      run: go build -v . 
    - name: Test
      run: go test -v ./...

    - name: Upload artifact
      if: inputs.upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: slopify
